spring.application.name=database

spring.output.ansi.enabled=ALWAYS

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://10.200.4.221:3306/yuri_mendes_ds?createDatabaseIfNotExist=true
spring.datasource.username=yuri_mendes
spring.datasource.password=aptecds